### ISSUE TITLE
Install haproxy from repo

### ISSUE THREAD

**Issue by patsevanton** [vitabaks/postgresql_cluster#14]
For Centos 7 install haproxy 1.8:
```
yum install centos-release-scl
yum install rh-haproxy18-haproxy rh-haproxy18-haproxy-syspaths
```

Oracle Linux:
https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/ 
for example:
https://www.thegeekdiary.com/how-to-enable-php-7-0-and-httpd24-on-oracle-linux-7/

RHEL:
https://www.softwarecollections.org/en/scls/rhscl/rh-haproxy18/

Debian/Ubuntu
https://haproxy.debian.net

**Comment by vitabaks** [comment]
It was decided to use HAProxy version 1.8 because of the ability to restart the HAProxy service without breaking the current connections that appeared in this version.
Details: https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/

We install HAProxy from the source code, as we support two families of Linux distributions (RedHat and Debian distributions), including different versions of these distributions.
Each version of the distribution has different versions of HAProxy (often very old versions), so we use the source code for the installation.

Thanks so much for the list of available repositories with HAProxy version 1.8.

We implement the ability to install HAProxy from rpm/deb packages from the repository. Since this installation method requires fewer dependent packages, unlike building from source code.
And also we will keep the ability to install from the source code if necessary.

**Comment by vitabaks** [comment]
See **dev** branch.

`git clone https://github.com/vitabaks/postgresql_cluster.git --branch dev`

Tested, works fine: Debian 9/10, Ubuntu 18.04 with Ansbile 2.8.6.

Must be tested on CentOS 7.6 distributions and OracleLinux.

@patsevanton @orisvscs 
I would be grateful if you could help me with testing these changes. 

What's new:
Now, HAProxy will be is installed from rpm/deb packages by default. The ability to install from source codes is saved.

See variables:
`haproxy_installation_method` and `haproxy_install_repo`

**Comment by vitabaks** [comment]
fyi:
You can also compile HAProxy version 2.0 from the source code.
https://github.com/vitabaks/postgresql_cluster/pull/15/commits/b690e46549ac67c0ef84072f79a1618871462ea6

**Comment by vitabaks** [comment]
SELinux is blocking keepalived scripts. 

> /bin/kill -0 `cat /var/run/haproxy/haproxy.pid` exited with status 1
>  Keepalived_vrrp[17834]: VRRP_Script(haproxy_check) failed

CentOS 7.

**Comment by patsevanton** [comment]
Cluster install. Work.
