### ISSUE TITLE
It's not evident how disabling of pg_rewind helps to prevent data loss under sync replication

### ISSUE THREAD

**Issue by maksm90** [vitabaks/postgresql_cluster#161]
Hi @vitabaks !

I'm some kind confused how turning off recovery of old master via pg_rewind will help to alleviate possible data loss under synchronous replication. AFAIK patroni will use pg_basebackup (a full uploading of database) to recover old master in case of unavailability of pg_rewind and effect will be the same. The single case when we might to prevent data loss under autofailover is to disable automatic turning old master to standby and allow user to manually transfer non-replicated changes from old master to the new one if it's possible, in general.

Also my critique regards to option synchronous_mode_strict = true. As I know, patroni will not automatically promote standby node treated as asynchronous in case when all standbys are asynchronous and synchronous_mode_strict = false. And the sole case when we might loss some data with respect to synchronous replication is to manually perform switchover to some asynchronous standby. 
But, perhaps, patroni doesn't detect the difference between standby node that just recently became synchronous in configuration but was not fully synchronized with master and really synchronized one. In this case when switchover occurs on that not already synchronized standby then we loss some last commits.

**Comment by vitabaks** [comment]
Hi @maksm90 

> patroni will use pg_basebackup (a full uploading of database) to recover old master in case of unavailability of pg_rewind 

This is new information for me, I need to check. Thanks.

> The single case when we might to prevent data loss under autofailover is to disable automatic turning old master to standby and allow user to manually transfer non-replicated changes from old master to the new one if it's possible, in general.

Yes, you're right, I'm trying to achieve this by disabling pg_rewind. It will be strange if Patroni simply overwrites the former leader...

> Also my critique regards to option synchronous_mode_strict = true. 

When it is absolutely necessary to guarantee that each write is stored durably on at least two nodes, enable synchronous_mode_strict in addition to the synchronous_mode. This parameter prevents Patroni from switching off the synchronous replication on the primary when no synchronous standby candidates are available. As a downside, the primary is not be available for writes (unless the Postgres transaction explicitly turns of synchronous_mode), blocking all client write requests until at least one synchronous replica comes up.

P.S.

Note: Because of the way synchronous replication is implemented in PostgreSQL it is still possible to lose transactions even when using synchronous_mode_strict. If the PostgreSQL backend is cancelled while waiting to acknowledge replication (as a result of packet cancellation due to client timeout or backend failure) transaction changes become visible for other backends. Such changes are not yet replicated and may be lost in case of standby promotion.

https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode

**Comment by vitabaks** [comment]
other parameters that you should pay attention to and not set them to true:

patroni_remove_data_directory_on_rewind_failure: false  # or 'true' (if use_pg_rewind: 'true')

> avoid removing the data directory on an unsuccessful rewind
> if 'true', Patroni will remove the PostgreSQL data directory and recreate the replica.

patroni_remove_data_directory_on_diverged_timelines: false  # or 'true'

> if 'true', Patroni will remove the PostgreSQL data directory and recreate the replica
> if it notices that timelines are diverging and the former master can not start streaming from the new master.

**Comment by maksm90** [comment]
> Note: Because of the way synchronous replication is implemented in PostgreSQL it is still possible to lose transactions even when using synchronous_mode_strict. If the PostgreSQL backend is cancelled while waiting to acknowledge replication (as a result of packet cancellation due to client timeout or backend failure) transaction changes become visible for other backends. Such changes are not yet replicated and may be lost in case of standby promotion.

Yes, you are completely right pointing in the doc paragraph (not in header) that we minimize the risk of data loss (but not prevent it). And in this sense the mention about `pg_rewind` is not relevant there.

> It will be strange if Patroni simply overwrites the former leader...

You have mentioned the patroni setting `remove_data_directory_on_diverged_timelines` doing this. It's disabled by default therefore my described behavior is less realistic than your suggesting state - preserving data directory of old master for manual recovery.

> When it is absolutely necessary to guarantee that each write is stored durably on at least two nodes, enable synchronous_mode_strict in addition to the synchronous_mode. This parameter prevents Patroni from switching off the synchronous replication on the primary when no synchronous standby candidates are available. As a downside, the primary is not be available for writes (unless the Postgres transaction explicitly turns of synchronous_mode), blocking all client write requests until at least one synchronous replica comes up.

The key point here is absolute necessity "to guarantee that each write is stored durably on at least two nodes". But IIRC in case of synchronous_mode_strict = false patroni will not perform automatic switchover to any asynchronous node. From user's point of view the machinery doesn't perform anything that losses data. It might be done manually by user. But here there is an issue to define that synchronous by configuration node is really synchronous (i.e., contains all committed changes). I don't know whether patroni is able to define the really synchronous state for standby that recently was setup to cluster after some time of disconnection to primary.

**Comment by vitabaks** [comment]
if `synchronous_mode_strict: true` - the primary is not be available for writes (unless the Postgres transaction explicitly turns of synchronous_mode), blocking all client write requests until at least one synchronous replica comes up.

due to this, it is guaranteed that the changes will not be lost, because it is forbidden to make changes if there is no synchronous replica.

**Comment by vitabaks** [comment]
it may also make sense to set the parameter `synchronous_commit: 'remote_apply'`

**Comment by maksm90** [comment]
> due to this, it is guaranteed that the changes will not be lost, because it is forbidden to make changes if there is no synchronous replica.

It guarantees that all changes will be replicated on master and synchronous standby even when the second is off-line. But if we reason about data loss in high availability cluster we have to account the possibility of master role moving on not synchronized standby. AFAIK, patroni doesn't allow to do this automatically if `synchronous_mode_strict: false` but as I mentioned I'm not sure about the case when synchronous by config standby node is in catching up state but is not really synchronized.

> it may also make sense to set the parameter synchronous_commit: 'remote_apply'

This option doesn't add anything to the persistence property for commits in cluster-wide environment compared to "remote flush" one. The last option corresponds to the state of synchronous standby when `synchromous_commit: on`. Both options persistently store commited changes in WAL of master and sync standbys. The difference is that the "remote apply" allows for users to see these changes on synchronous standby earlier than on master node.
