### ISSUE TITLE
Updating to Ubuntu 22.04

### ISSUE THREAD

**Issue by davidpanic** [vitabaks/postgresql_cluster#196]
I have a cluster running on machines with Ubuntu 20.04.5 installed. I would like to update to Ubuntu 22.04.1, but when doing so on one machine the Patroni service simply will not start any more. How would I go about correctly updating Patroni, seeing that this playbook does not support updating the cluster, only installing. Would I have to recreate the cluster, because that would be a royal pain in the ass considering we have A LOT of data stored in the databases?

Here is the systemd service log for the patroni service:
```
Aug 29 13:56:09 pg13-3 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - patroni.
Aug 29 13:56:10 pg13-3 patroni[732]: Traceback (most recent call last):
Aug 29 13:56:10 pg13-3 patroni[732]:   File "/usr/local/bin/patroni", line 5, in <module>
Aug 29 13:56:10 pg13-3 patroni[732]:     from patroni import main
Aug 29 13:56:10 pg13-3 patroni[732]: ModuleNotFoundError: No module named 'patroni'
Aug 29 13:56:10 pg13-3 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 13:56:10 pg13-3 systemd[1]: patroni.service: Failed with result 'exit-code'.
```

**Comment by vitabaks** [comment]
Hi @davidpanic !

I were you, I would create separate servers with ubuntu 22.04 and add them to the current cluster. Then perform a switchover to one of the replicas on the new server 22.04 and then turn off the 20.04 servers.

use `add_pgnode.yml` and `add_balancer.yml` playbooks.

details: https://github.com/vitabaks/postgresql_cluster#cluster-scaling 

Additionally:

After the update to the new glibc version (for example, update the operating system). \
Check the b-tree indexes using the amcheck extension and reindex all corrupted indexes. It is also recommended to reindex all other (non b-tree) indexes because they cannot be checked with amcheck.

**Comment by davidpanic** [comment]
Ah, thanks, I had a similar procedure in my head. Quick question about the glibc update, my servers are already running glibc 2.31, would I still need to reindex stuff because IIRC the locale changes happened on glibc 2.28. Are there any other changes that I am unaware of?

**Comment by vitabaks** [comment]
check your indexes every time the glibc version changes
