### ISSUE TITLE
test [Type B] PostgreSQL High-Availability only

### ISSUE THREAD

**Issue by fatmaAliGamal** [vitabaks/postgresql_cluster#390]
when i test [Type B] PostgreSQL High-Availability only
using sudo systemctl stop postgresql.service at primary server
no replica change from secondary to primary to cover failover

 attach Patroni logs. i can't find logs of patroni
(https://github.com/vitabaks/postgresql_cluster/assets/45911031/fd641324-1032-4935-acf1-4150cd91bf22)

**Comment by fatmaAliGamal** [comment]
@vitabaks thanks when i use sudo systemctl stop postgresql.service , if any request to write still write at primary but when i stop machine that represent primary server , one of the replica act as primary 
thanks alot for repo

**Comment by vitabaks** [comment]
In cluster mode, there is no need to stop pistgres using systemctl, since it is managed by Patroni. 

You can stop the patroni service or database server.

**Comment by vitabaks** [comment]
@fatmaAliGamal 

Please consider [sponsoring](https://github.com/vitabaks/postgresql_cluster#sponsor-this-project) this project. It is necessary that this open source project become even better, so that more functionality and automation are added.

Some membership levels include live chat with me and personalized support.

**Comment by fatmaAliGamal** [comment]
Thanks Vitabaks/Postgresql_cluster for all your help
