### ISSUE TITLE
ansible error 

### ISSUE THREAD

**Issue by ayadahm** [vitabaks/postgresql_cluster#615]
Hi Vitabaks
I got the following error When trying to run ansible-playbook deploy_pgcluster.yml.
My choice was 
pgbouncer_install: false 
and I did not ON any postgresql_parameters  on main.yml (assuming that postgresql will be installed with default parameters from postgresql.conf)

Should I choose the minimun max_connections from the list in mail.yml ?? why ?

```
TASK [pre-checks : Set max_connections from vars or use default] **************************************************************************
task path: /--/--/--/--/--/postgresql_cluster/roles/pre-checks/tasks/pgbouncer.yml:5
fatal: [195.231.167.54]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

**Comment by vitabaks** [comment]
Hi @ayadahm ! I'll check it out.

**Comment by ayadahm** [comment]
Many thanks. 

There is also an error if I choose pg_stat_statements for installation from the list of extensions.

**Comment by vitabaks** [comment]
@ayadahm I have not been able to reproduce the issue with the pgbouncer pre-check.

please attach an archive of your variable files so that I can study them.

**Comment by ayadahm** [comment]
[main.txt](https://github.com/vitabaks/postgresql_cluster/files/14805103/main.txt)

**Comment by vitabaks** [comment]
@ayadahm I'm sorry for the long answer.

Is this problem still relevant?

**Comment by ayadahm** [comment]
Hi yesterday

**Comment by SDV109** [comment]
@ayadahm Hi!
You made mistakes in vars/main.yml in each of the cases you described:
1) When you commented out all the points of postgresql_parameters, you violated the syntax of yaml files, because after: you need to specify either a specific value or list it, and you get to comment out the list, but did not indicate that in your case postgresql_patameters is empty, for this you need to make the following postgresql_parameters construction
: [] - this construction indicates that nothing is used from postgresql_parameters in this example.
But in this case, there is an error in the algorithm, I will inform @vitabaks for correction, but I think that most likely according to the further algorithm, there would also be other errors due to the syntax.
To summarize, you need to change main.yml like this:
```
postgresql_parameters: []
#  - { option: "max_connections", value: "500" }
``` 
2) In the second case, there is a YML syntax error again, and you are specifically told:
/home/am/ANSIBLE/new_unilogin/patroni_from_github/postgresql_cluster/vars/main.yml': line 175, column 3
Ansible errors, of course, do not always describe exactly how to make a correction, but most often indicate the place where the correction needs to be made.  
```
postgresql_extensions: []
  - { ext: "pg_stat_statements", db: "postgres" }
``` 
In your case, the error was that you passed as postgresql_extensions with an empty list, and after the postgresql_extensions variable, you have - {ext: "pg_stat_statements", db: "postgres"}, which ansible cannot recognize, since it is part of the list, and the variable is not open for lists.
To summarize, you need to change main.yml like this:
```
postgresql_extensions: 
  - { ext: "pg_stat_statements", db: "postgres" }
```

**Comment by vitabaks** [comment]
Thanks @SDV109

**Comment by ayadahm** [comment]
Many thanks for the correction. I will try that out. Cheers.

**Comment by vitabaks** [comment]
Is the problem still relevant?

**Comment by ayadahm** [comment]
Hi no not any more. Great work!
