### ISSUE TITLE
system.yaml

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/postgresql_cluster#752]
It's not recommended to enable swap in postgres, why it is enabled by default?
>swap_file_create: true 
swap_file_path: /swapfile
swap_file_size_mb: '4096'  # change this value for your system

With which parameters of OS is intended sysctl_conf? 
or is this for systems with any parameters?
>sysctl_conf:
postgres_cluster:
    - { name: "vm.overcommit_memory", value: "2" }
    - { name: "vm.swappiness", value: "1" }
    - { name: "vm.min_free_kbytes", value: "102400" }
    - { name: "vm.dirty_expire_centisecs", value: "1000" }
    - { name: "vm.dirty_background_bytes", value: "67108864" }
    - { name: "vm.dirty_bytes", value: "536870912" }
>/#    - { name: "vm.nr_hugepages", value: "9510" }  # example "9510"=18GB
    - { name: "vm.zone_reclaim_mode", value: "0" }
    - { name: "kernel.numa_balancing", value: "0" }
    - { name: "kernel.sched_autogroup_enabled", value: "0" }
    - { name: "net.ipv4.ip_nonlocal_bind", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv4.ip_local_port_range", value: "10000 65535" }
    - { name: "net.core.netdev_max_backlog", value: "10000" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "8192" }
    - { name: "net.core.somaxconn", value: "65535" }
    - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
  balancers:
    - { name: "net.ipv4.ip_nonlocal_bind", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv4.ip_local_port_range", value: "10000 65535" }
    - { name: "net.core.netdev_max_backlog", value: "10000" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "8192" }
    - { name: "net.core.somaxconn", value: "65535" }
    - { name: "net.ipv4.tcp_tw_reuse", value: "1" }

How to correctly configure this parameters?
Thanks!

**Comment by vitabaks** [comment]
Swap is important for all Linux systems, including databases, for several reasons:

1. **Prevention of system crashes**: Swap acts as a safety net when the system runs out of physical memory. Even if the system typically has enough RAM, sudden spikes in memory usage can cause issues. In such cases, swap can prevent the system from invoking the Out of Memory (OOM) killer, which could terminate critical processes, including database processes, leading to unexpected crashes.

2. **Memory optimization**: Swap allows for more efficient use of physical memory. It offloads less frequently accessed data to swap space, freeing up RAM for more performance-critical tasks. This is especially useful for background processes that don't require constant access to RAM.

However, constant use of swap is undesirable because accessing data from swap is significantly slower than accessing it from RAM. To mitigate this, the "`vm.swappiness`" parameter is often set to a low value, such as `1`, meaning the system will only use swap as a last resort when RAM is fully utilized.

The kernel parameters provided in the `sysctl_conf` variable are optimal for most Postgres database servers (in my opinion), but you can override them if you know what you are doing or disable them altogether.

**Comment by algoritmsystems** [comment]
I would also add here shmmax / shmall for shared memory:
https://postgrespro.com/list/thread-id/1155670

>#!/bin/bash
# Output lines suitable for sysctl configuration based
# on total amount of RAM on the system.  The output
# will allow up to 50% of physical memory to be allocated
# into shared memory.
#
# On Linux, you can use it as follows (as root):
#
# ./shmsetup >> /etc/sysctl.conf
# sysctl -p
#
# Early FreeBSD versions do not support the sysconf interface
# used here.  The exact version where this works hasn't
# been confirmed yet.
#
page_size=`getconf PAGE_SIZE`
phys_pages=`getconf _PHYS_PAGES`
#
if [ -z "$page_size" ]; then
  echo Error:  cannot determine page size
  exit 1
fi
#
if [ -z "$phys_pages" ]; then
  echo Error:  cannot determine number of memory pages
  exit 2
fi
#
shmall=`expr $phys_pages / 2`
shmmax=`expr $shmall \* $page_size`
#
echo \# Maximum shared segment size in bytes
echo kernel.shmmax = $shmmax
echo \# Maximum number of shared memory segments in pages
echo kernel.shmall = $shmall
