### ISSUE TITLE
How to correctly change postgresql.conf

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/postgresql_cluster#755]
I've got my cluster up and running and need to change a few parameters in the postgresql.conf file. 
How can I change the values ​​of parameters in this file or in pg_hba.conf? 
Is it enough to change this on the master by stopping all the nodes in the cluster first and run then patrony, or it shoulde be changed in each replicas too?
Thanks!

**Comment by vitabaks** [comment]
Please read the documentation https://postgresql-cluster.org/management/configuration

**Comment by Jamic28** [comment]
Well I change the settings in the /vars/main.yaml file and run just:
>ansible-playbook config_pgcluster.yml. 

The playbook will update my settings on all cluster nodes and restart all the necessary services, right?

**Comment by vitabaks** [comment]
right

**Comment by Jamic28** [comment]
Thank you @vitabaks !
What about updating minor version postgre_cluster. Say I'm using v1.3.0 version and now released v1.4.1. To upgrade to the newest version first it's clonning the new version from git, then change inventory file by coping it from the older directory from were last deploy and change other files if needed (main.yaml, system.yaml...) and  then should be run:
>ansible-playbook update_pgcluster.yml -e target=system
>?

**Comment by vitabaks** [comment]
> What about updating minor version postgre_cluster

`postgresql_cluster` is automation code (based on ansible), so to update it, you only need to replace the automation directory while carefully reviewing the variable files in the `vars` directory. In fact, your clusters differ in variables and the inventory file.

And then it will be easier to launch the playbook `deploy_pgcluster.yml` with the variable `postgresql_exists` in order to re-insert all the components without affecting the data, so the cluster state will correspond to the new version of the automation code.

```
ansible-playbook deploy_pgcluster.yml -e "postgresql_exists =true"
```

> Say I'm using v1.3.0 version and now released v1.4.1. 

I hope you are not using such an old version. I recommend using a version no older than 1.11.0. See [Release notes](https://github.com/vitabaks/postgresql_cluster/releases)

**Comment by vitabaks** [comment]
> So to update just configuration it's running:

https://postgresql-cluster.org/management/configuration

> to update components of the cluster :

https://postgresql-cluster.org/management/upgrades

**Comment by Jamic28** [comment]
Thanks!
