### ISSUE TITLE
How to configure synchronous backup from the cluster

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/postgresql_cluster#757]
Which utility is recomended in production to synchronously backup from the postgresql cluster (not replica) incrementally or differentially to the remote server automatically without configuring any cronjobs?
Thanks!

**Comment by vitabaks** [comment]
What task do you want to do this for? Can you describe it in more detail?

If you are talking about a clone for development and tests, then [DBLab Engine](https://github.com/postgres-ai/database-lab-engine) will suit you.

**Comment by algoritmsystems** [comment]
There's no any backup utility that works as syncronous replica, there will still be a delay because all the walls will first be written to the master and then transferred to the backup. Below is the list that may suit you, but backup mechanism of all of them is asynchronous:
https://github.com/postgrespro/pg_probackup
https://github.com/Aiven-Open/pghoard
https://github.com/EnterpriseDB/barman
https://github.com/pgbackrest/pgbackrest
https://github.com/wal-g/wal-g
