### ISSUE TITLE
Support Consul for distributed consensus

### ISSUE THREAD

**Issue by RashadAnsari** [vitabaks/postgresql_cluster#85]
Can you please support <a href="https://www.consul.io/">Consul</a> as a distributed consensus store?

**Comment by asobeeh** [comment]
any update about supporting consul please

**Comment by vitabaks** [comment]
I do not plan to implement and maintain code to deploy the Consul cluster, instead we can use this playback https://github.com/ansible-community/ansible-consul 
I will add variables to configure interaction with the Consul.
In addition, we need to configure the connection with Consul and test the operation of these components: confd for the [[Type A](https://github.com/vitabaks/postgresql_cluster#type-a-postgresql-high-availability-with-load-balancing)] schema, VIP-Manager for the [[Type B](https://github.com/vitabaks/postgresql_cluster#type-b-postgresql-high-availability-only)] schema (if variable cluster_vip is specified).

I'll do it right away as soon as I can allocate more time.
I appreciate any help.

**Comment by asobeeh** [comment]
Thanks For your update,
and for your info i installed consul cluster manually and changed that in patroni.yml file the part of etcd: hosts with consul and changed with consul ports 
and restarted patroni and worked with no issues.
as I faced an issues with etcd and could not solve it so I changed to consul

**Comment by vitabaks** [comment]
> as I faced an issues with etcd and could not solve it so I changed to consul

etcd is very reliable, usually there are no problems with it. If you encountered a problem, do not hesitate to open a new issue.

**Comment by asobeeh** [comment]
> > as I faced an issues with etcd and could not solve it so I changed to consul
> 
> etcd is very reliable, usually there are no problems with it. If you encountered a problem, do not hesitate to open a new issue.

really u appreciate your support regarding that 
and my issue in etcd was in cluster 
as both of etcd service running on both servers but one of them facing an issue of "CRITICAL: system ID mismatch, node belongs to a different cluster:"
I even tried to remove everything and reinstall it again with no luck 
I checked all possible solution for that issue but no luck 
that's why I use consul

**Comment by vitabaks** [comment]
I’m studying the work of Consul [Service Discovery](https://www.consul.io/use-cases/discover-services) with [DNS resolving ](https://developer.hashicorp.com/consul/docs/discovery/dns) and I’m starting to like it.

It is convenient to search for the master and replicas (without using vip-manager or haproxy), although there are questions about balancing to replicas.
Nevertheless, it can be useful for a distributed cluster across different data centers. We can specify in advance which data center the database server is located in and then use this for applications running in the same data center.

And, we can add any custom checks so that the service is considered healthy and the DNS record for this service is active.

I'm thinking of adding a new type of schema: "**[Type C] PostgreSQL High-Availability with Service Discovery (DNS)**" based on "Patroni" and "Consul".

I'm thinking of doing it!

**Comment by vitabaks** [comment]
cc @askurihin

**Comment by vitabaks** [comment]
Done.
